STARTED_DATE_JSON_NAME = "started_at"
FINISHED_DATE_JSON_NAME = "finished_at"
DELETED_DATE_JSON_NAME = "deleted_at"
FILE_NAME_JSON_NAME = "file_name"
STATUS_JSON_NAME = "status"
LENGTH_JSON_NAME = "length"
CHUNK_SIZE_BYTES_JSON_NAME = "chunk_size"

FILE_ID_JSON_NAME = "file_id"
NUM_JSON_NAME = "num"
DATA_JSON_NAME = "data"

DEFAULT_CHUNK_SIZE = 255 * 1024
